version: 2.1

executors:
  deploy-executor:
    docker:
      - image: google/cloud-sdk:latest
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: docker-executor
    steps:
      - checkout

  build_docker_image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate to GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker

      - run:
          name: Build Docker Image and Push Image to GCP Container Registry
          command: |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/section7-mlops/section7-mlops:latest .
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/section7-mlops/section7-mlops:latest


  deploy_to_gke:
    executor: deploy-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate to GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev || gcloud auth configure-docker

      - run:
          name: Configure GKE
          command: |
            gcloud container clusters get-credentials $GKE_CLUSTER --zone $GOOGLE_COMPUTE_ZONE --project $GOOGLE_PROJECT_ID
            kubectl apply -f kubernetes-deployment.yaml

      - run:
          name: Deploy to GKE
          command: |
            kubectl apply -f kubernetes-deployment.yaml --record
            

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image